##############################################################
# Document: https://gohugo.io/getting-started/configuration/ #
##############################################################

# The URL of the site
# Hostname (and path) to the root, e.g. https://bep.is/
baseURL = "http://localhost:1313/"

# The name of theme in `/themes/`.
theme = "hugo-bulma"

# Google Analytics tracking ID.
googleAnalytics = ""

# Disable Hugo generator meta tag in the HTML head.
disableHugoGeneratorInject =  true

# Default language to use.
defaultContentLanguage = "en"

# Render the default content language in subdir, e.g. /en/. 
defaultContentLanguageInSubdir = true

# Set `true` for Chinese/Japanese/Korean languages.
hasCJKLanguage = true                   

# Workaround for https://github.com/gohugoio/hugo/issues/5687.
removePathAccents = true                

# Enable Emoji emoticons support for page content.
enableEmoji = true

# The number of elements per page in pagination.
paginate = 10

# Listing summary length in words.
summaryLength = 30  

# Markdown.
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            # Enable user to embed HTML snippets in Markdown content.
            unsafe = true

[outputs]
    home = [ "HTML", "RSS", "JSON", "MANIFEST" ]
    section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.MANIFEST]
    mediaType = "application/manifest+json"
    rel = "manifest"
    notAlternative = true
