[en]
    weight          = 1
    languageCode    = "en"
    languageName    = "English"
    contentDir      = "content/en"

    # The copyright notice to display in the site footer.
    # To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
    copyright       = "&copy; {year} Wayne Ho"

    # The title of site
    title           = "Hugo-Bulma: Hugo theme based on Bulma" 

    [en.params]
        author = "Wayne Ho"
        keywords = "Hugo-Bulma, Hugo, Bulma, Theme"
        description = "Hugo-Bulma is a free, open source Hugo theme based on Bulma."

[zh]
    weight          = 2
    languageCode    = "zh"
    languageName    = "中文"
    contentDir      = "content/zh"

    copyright       = "&copy; {year} Wayne Ho"
    title           = "Hugo-Bulma主题"

    [zh.params]
        author = "Wayne Ho"
        keywords = "Hugo-Bulma, Hugo, Bulma, 主题"
        description = "Hugo-Bulma是一个基于Bulma的Hugo主题，并且完全开源、免费。"
