[[navbar]]
    identifier = "home"
    weight = 1
    name = "主页"
    url = "/"
    pre = "<span class=\"icon is-medium\"><i class=\"fas fa-home\"></i></span>"


[[navbar]]
    identifier = "github"
    weight = 99
    name = "GitHub"
    url = "https://github.com/wayn3h0/hugo-bulma"
    pre = "<span class=\"icon\"><i class=\"fab fa-github\"></i></span>"


