[[navbar]]
    identifier = "home"
    weight = 1
    name = "Home"
    url = "/"
    pre = "<span class=\"icon\"><i class=\"fas fa-home\"></i></span>"

[[navbar]]
    identifier = "documentation"
    weight = 2
    name = "Documentation"
    url = "documentation/"
    pre = "<span class=\"icon\"><i class=\"fas fa-book\"></i></span>"

[[navbar]]
    identifier = "github"
    weight = 99
    name = "GitHub"
    url = "https://github.com/wayn3h0/hugo-bulma"
    pre = "<span class=\"icon\"><i class=\"fab fa-github\"></i></span>"


[[legal]]
    identifier = "terms-of-use"
    weight = 1
    name = "Terms of Use"
    url = "/terms-of-use/"

[[legal]]
    identifier = "terms-of-conditions"
    weight = 2
    name = "Terms of Conditions"
    url = "/terms-of-conditions/"

[[legal]]
    identifier = "privacy-policy"
    weight = 3
    name = "Privacy Policy"
    url = "/privacy-policy/"


[[quicklinks]]
    identifier = "documentation"
    weight = 1
    name = "DOCUMENTATION"

[[quicklinks]]
    identifier = "follow-us"
    weight = 2
    name = "FOLLOW US"

[[quicklinks]]
    identifier = "twitter"
    parent = "follow-us"
    weight = 1
    name = "Twitter"
    url = "#"
    pre = "<span class=\"icon\"><i class=\"fab fa-twitter\"></i></span>"

[[quicklinks]]
    identifier = "facebook"
    parent = "follow-us"
    weight = 2
    name = "Facebook"
    url = "#"
    pre = "<span class=\"icon\"><i class=\"fab fa-facebook\"></i></span>"

